# Generated by Django 3.0.8 on 2020-08-03 04:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studylog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 4, 38, 46, 951324, tzinfo=utc)),
        ),
    ]
