# Generated by Django 3.0.8 on 2020-08-03 04:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20200803_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studylog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
