# Generated by Django 3.0.8 on 2020-08-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20200803_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyuser',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
