# Generated by Django 3.0.8 on 2020-08-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_auto_20200803_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studylog',
            name='user',
            field=models.CharField(max_length=40),
        ),
        migrations.DeleteModel(
            name='StudyUser',
        ),
    ]
