# Generated by Django 3.0.8 on 2020-08-03 09:31

from django.db import migrations, models
import study.models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_auto_20200803_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='studylog',
            name='next_review_date',
            field=models.DateTimeField(default=study.models.days_hence),
        ),
    ]
